[2025-04-23T07:05:00.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T07:05:00.468+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:04:00+00:00 [queued]>
[2025-04-23T07:05:00.471+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:04:00+00:00 [queued]>
[2025-04-23T07:05:00.472+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T07:05:00.478+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): create_tables> on 2025-04-23 07:04:00+00:00
[2025-04-23T07:05:00.484+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13136) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T07:05:00.485+0000] {standard_task_runner.py:72} INFO - Started process 13138 to run task
[2025-04-23T07:05:00.485+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data', 'create_tables', 'scheduled__2025-04-23T07:04:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/el_30min.py', '--cfg-path', '/tmp/tmp_af3d0m2']
[2025-04-23T07:05:00.487+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask create_tables
[2025-04-23T07:05:00.510+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:04:00+00:00 [running]> on host eb276ba0497d
[2025-04-23T07:05:00.547+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T07:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T07:04:00+00:00'
[2025-04-23T07:05:00.548+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T07:05:00.553+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T07:05:00.556+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T07:05:00.561+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T07:05:00.561+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data, task_id=create_tables, run_id=scheduled__2025-04-23T07:04:00+00:00, execution_date=20250423T070400, start_date=20250423T070500, end_date=20250423T070500
[2025-04-23T07:05:00.618+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T07:05:00.633+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T07:05:00.634+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
