[2025-04-23T07:14:00.957+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T07:14:00.964+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:13:00+00:00 [queued]>
[2025-04-23T07:14:00.967+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:13:00+00:00 [queued]>
[2025-04-23T07:14:00.967+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T07:14:00.973+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): create_tables> on 2025-04-23 07:13:00+00:00
[2025-04-23T07:14:00.980+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14188) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T07:14:00.980+0000] {standard_task_runner.py:72} INFO - Started process 14190 to run task
[2025-04-23T07:14:00.981+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data', 'create_tables', 'scheduled__2025-04-23T07:13:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/el_30min.py', '--cfg-path', '/tmp/tmp6wqu63dp']
[2025-04-23T07:14:00.982+0000] {standard_task_runner.py:105} INFO - Job 122: Subtask create_tables
[2025-04-23T07:14:01.004+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data.create_tables scheduled__2025-04-23T07:13:00+00:00 [running]> on host eb276ba0497d
[2025-04-23T07:14:01.041+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T07:13:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T07:13:00+00:00'
[2025-04-23T07:14:01.042+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T07:14:01.047+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T07:14:01.050+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T07:14:01.054+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T07:14:01.055+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data, task_id=create_tables, run_id=scheduled__2025-04-23T07:13:00+00:00, execution_date=20250423T071300, start_date=20250423T071400, end_date=20250423T071401
[2025-04-23T07:14:01.073+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T07:14:01.087+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T07:14:01.088+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
