[2025-04-23T11:02:45.503+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T11:02:45.513+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:57:01.209842+00:00 [queued]>
[2025-04-23T11:02:45.517+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:57:01.209842+00:00 [queued]>
[2025-04-23T11:02:45.517+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 5
[2025-04-23T11:02:45.523+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): dbt_task_group.stg_weather_data_run> on 2025-04-23 10:57:01.209842+00:00
[2025-04-23T11:02:45.529+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14240) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T11:02:45.530+0000] {standard_task_runner.py:72} INFO - Started process 14242 to run task
[2025-04-23T11:02:45.530+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_transform', 'dbt_task_group.stg_weather_data_run', 'manual__2025-04-23T10:57:01.209842+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/dbtdag.py', '--cfg-path', '/tmp/tmpk_mpunpa']
[2025-04-23T11:02:45.530+0000] {standard_task_runner.py:105} INFO - Job 324: Subtask dbt_task_group.stg_weather_data_run
[2025-04-23T11:02:45.552+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:57:01.209842+00:00 [running]> on host eb276ba0497d
[2025-04-23T11:02:45.594+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transform' AIRFLOW_CTX_TASK_ID='dbt_task_group.stg_weather_data_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T10:57:01.209842+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T10:57:01.209842+00:00'
[2025-04-23T11:02:45.596+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T11:02:46.233+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-23T11:02:46.233+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmpoaxm3bi2 from /opt/airflow/dags/dbt/weather
[2025-04-23T11:02:46.234+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dbt_transform__dbt_task_group/target/partial_parse.msgpack
[2025-04-23T11:02:46.238+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-23T11:02:46.242+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T11:02:46.243+0000] {config.py:340} INFO - Profile found in cache using profile: /tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3/profiles.yml.
[2025-04-23T11:02:46.245+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['deps', '--project-dir', '/tmp/tmpoaxm3bi2', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpoaxm3bi2
[2025-04-23T11:02:46.272+0000] {logging_mixin.py:190} INFO - 11:02:46  Running with dbt=1.8.7
[2025-04-23T11:02:46.883+0000] {logging_mixin.py:190} INFO - 11:02:46  Installing dbt-labs/dbt_utils
[2025-04-23T11:02:47.733+0000] {logging_mixin.py:190} INFO - 11:02:47  Installed from version 0.9.6
[2025-04-23T11:02:47.734+0000] {logging_mixin.py:190} INFO - 11:02:47  Updated version available: 1.3.0
[2025-04-23T11:02:47.734+0000] {logging_mixin.py:190} INFO - 11:02:47
[2025-04-23T11:02:47.735+0000] {logging_mixin.py:190} INFO - 11:02:47  Updates available for packages: ['dbt-labs/dbt_utils']                 
Update your versions in packages.yml, then run dbt deps
[2025-04-23T11:02:48.975+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stg_weather_data', '--project-dir', '/tmp/tmpoaxm3bi2', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpoaxm3bi2
[2025-04-23T11:02:48.979+0000] {logging_mixin.py:190} INFO - 11:02:48  Running with dbt=1.8.7
[2025-04-23T11:02:49.046+0000] {logging_mixin.py:190} INFO - 11:02:49  Registered adapter: postgres=1.9.0
[2025-04-23T11:02:49.412+0000] {logging_mixin.py:190} INFO - 11:02:49  Found 5 models, 626 macros
[2025-04-23T11:02:49.413+0000] {logging_mixin.py:190} INFO - 11:02:49
[2025-04-23T11:02:49.453+0000] {logging_mixin.py:190} INFO - 11:02:49  Concurrency: 1 threads (target='dev')
[2025-04-23T11:02:49.454+0000] {logging_mixin.py:190} INFO - 11:02:49
[2025-04-23T11:02:49.455+0000] {logging_mixin.py:190} INFO - 11:02:49  1 of 1 START sql view model transformed.stg_weather_data ....................... [RUN]
[2025-04-23T11:02:49.505+0000] {logging_mixin.py:190} INFO - 11:02:49  1 of 1 OK created sql view model transformed.stg_weather_data .................. [CREATE VIEW in 0.05s]
[2025-04-23T11:02:49.511+0000] {logging_mixin.py:190} INFO - 11:02:49
[2025-04-23T11:02:49.511+0000] {logging_mixin.py:190} INFO - 11:02:49  Finished running 1 view model in 0 hours 0 minutes and 0.10 seconds (0.10s).
[2025-04-23T11:02:49.527+0000] {logging_mixin.py:190} INFO - 11:02:49
[2025-04-23T11:02:49.527+0000] {logging_mixin.py:190} INFO - 11:02:49  Completed successfully
[2025-04-23T11:02:49.527+0000] {logging_mixin.py:190} INFO - 11:02:49
[2025-04-23T11:02:49.527+0000] {logging_mixin.py:190} INFO - 11:02:49  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-23T11:02:50.601+0000] {local.py:465} INFO - Inlets: []
[2025-04-23T11:02:50.601+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra=None)]
[2025-04-23T11:02:50.601+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-23T11:02:50.624+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T11:02:50.625+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_transform, task_id=dbt_task_group.stg_weather_data_run, run_id=manual__2025-04-23T10:57:01.209842+00:00, execution_date=20250423T105701, start_date=20250423T110245, end_date=20250423T110250
[2025-04-23T11:02:50.628+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra={}) through aliases "dbt_transform__dbt_task_group__stg_weather_data_run"
[2025-04-23T11:02:50.696+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T11:02:50.710+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T11:02:50.711+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
