[2025-04-23T09:35:30.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T09:35:30.811+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.load_backfill_data_4 manual__2025-04-23T09:31:00.792292+00:00 [queued]>
[2025-04-23T09:35:30.815+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.load_backfill_data_4 manual__2025-04-23T09:31:00.792292+00:00 [queued]>
[2025-04-23T09:35:30.815+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-04-23T09:35:30.821+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_backfill_data_4> on 2025-04-23 09:31:00.792292+00:00
[2025-04-23T09:35:30.827+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5983) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T09:35:30.828+0000] {standard_task_runner.py:72} INFO - Started process 5985 to run task
[2025-04-23T09:35:30.828+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'load_backfill_data_4', 'manual__2025-04-23T09:31:00.792292+00:00', '--job-id', '240', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmpgzqabf0j']
[2025-04-23T09:35:30.829+0000] {standard_task_runner.py:105} INFO - Job 240: Subtask load_backfill_data_4
[2025-04-23T09:35:30.851+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.load_backfill_data_4 manual__2025-04-23T09:31:00.792292+00:00 [running]> on host eb276ba0497d
[2025-04-23T09:35:30.939+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='load_backfill_data_4' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T09:31:00.792292+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T09:31:00.792292+00:00'
[2025-04-23T09:35:30.940+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T09:35:30.954+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T09:35:30.959+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T09:35:30.959+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data_daily, task_id=load_backfill_data_4, run_id=manual__2025-04-23T09:31:00.792292+00:00, execution_date=20250423T093100, start_date=20250423T093530, end_date=20250423T093530
[2025-04-23T09:35:31.000+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T09:35:31.012+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T09:35:31.013+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
