[2025-04-23T09:16:29.348+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T09:16:29.357+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.load_to_postgres manual__2025-04-23T09:16:27.549652+00:00 [queued]>
[2025-04-23T09:16:29.360+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.load_to_postgres manual__2025-04-23T09:16:27.549652+00:00 [queued]>
[2025-04-23T09:16:29.360+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T09:16:29.366+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_to_postgres> on 2025-04-23 09:16:27.549652+00:00
[2025-04-23T09:16:29.372+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3680) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T09:16:29.373+0000] {standard_task_runner.py:72} INFO - Started process 3682 to run task
[2025-04-23T09:16:29.373+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'load_to_postgres', 'manual__2025-04-23T09:16:27.549652+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmpqjpkqnl4']
[2025-04-23T09:16:29.374+0000] {standard_task_runner.py:105} INFO - Job 188: Subtask load_to_postgres
[2025-04-23T09:16:29.396+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.load_to_postgres manual__2025-04-23T09:16:27.549652+00:00 [running]> on host eb276ba0497d
[2025-04-23T09:16:29.488+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T09:16:27.549652+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T09:16:27.549652+00:00'
[2025-04-23T09:16:29.489+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T09:16:29.506+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T09:16:29.511+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T09:16:29.511+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data_daily, task_id=load_to_postgres, run_id=manual__2025-04-23T09:16:27.549652+00:00, execution_date=20250423T091627, start_date=20250423T091629, end_date=20250423T091629
[2025-04-23T09:16:29.545+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T09:16:29.554+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T09:16:29.555+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
