[2025-04-23T09:36:58.425+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T09:36:58.435+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.branch_table_check manual__2025-04-23T09:31:00.792292+00:00 [queued]>
[2025-04-23T09:36:58.439+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.branch_table_check manual__2025-04-23T09:31:00.792292+00:00 [queued]>
[2025-04-23T09:36:58.439+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 5
[2025-04-23T09:36:58.445+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branch_table_check> on 2025-04-23 09:31:00.792292+00:00
[2025-04-23T09:36:58.451+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=6137) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T09:36:58.452+0000] {standard_task_runner.py:72} INFO - Started process 6139 to run task
[2025-04-23T09:36:58.452+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'branch_table_check', 'manual__2025-04-23T09:31:00.792292+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmpozgyp8lv']
[2025-04-23T09:36:58.454+0000] {standard_task_runner.py:105} INFO - Job 242: Subtask branch_table_check
[2025-04-23T09:36:58.476+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.branch_table_check manual__2025-04-23T09:31:00.792292+00:00 [running]> on host eb276ba0497d
[2025-04-23T09:36:58.519+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='branch_table_check' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T09:31:00.792292+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T09:31:00.792292+00:00'
[2025-04-23T09:36:58.520+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T09:36:58.521+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-23T09:36:58.525+0000] {python.py:240} INFO - Done. Returned value was: extract_today_branch
[2025-04-23T09:36:58.526+0000] {branch.py:38} INFO - Branch into extract_today_branch
[2025-04-23T09:36:58.526+0000] {skipmixin.py:233} INFO - Following branch ('extract_today_branch',)
[2025-04-23T09:36:58.530+0000] {skipmixin.py:281} INFO - Skipping tasks [('extract_backfill_branch', -1)]
[2025-04-23T09:36:58.545+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T09:36:58.545+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data_daily, task_id=branch_table_check, run_id=manual__2025-04-23T09:31:00.792292+00:00, execution_date=20250423T093100, start_date=20250423T093658, end_date=20250423T093658
[2025-04-23T09:36:58.585+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T09:36:58.604+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T09:36:58.607+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
