[2025-04-23T10:47:04.953+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T10:47:04.964+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.fact_weather_data_run manual__2025-04-23T10:46:42.794055+00:00 [queued]>
[2025-04-23T10:47:04.969+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.fact_weather_data_run manual__2025-04-23T10:46:42.794055+00:00 [queued]>
[2025-04-23T10:47:04.969+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-23T10:47:04.975+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): dbt_task_group.fact_weather_data_run> on 2025-04-23 10:46:42.794055+00:00
[2025-04-23T10:47:04.981+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=12641) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T10:47:04.981+0000] {standard_task_runner.py:72} INFO - Started process 12642 to run task
[2025-04-23T10:47:04.982+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_transform', 'dbt_task_group.fact_weather_data_run', 'manual__2025-04-23T10:46:42.794055+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/dbtdag.py', '--cfg-path', '/tmp/tmpuvcbgopd']
[2025-04-23T10:47:04.983+0000] {standard_task_runner.py:105} INFO - Job 309: Subtask dbt_task_group.fact_weather_data_run
[2025-04-23T10:47:05.006+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_transform.dbt_task_group.fact_weather_data_run manual__2025-04-23T10:46:42.794055+00:00 [running]> on host eb276ba0497d
[2025-04-23T10:47:05.046+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transform' AIRFLOW_CTX_TASK_ID='dbt_task_group.fact_weather_data_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T10:46:42.794055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T10:46:42.794055+00:00'
[2025-04-23T10:47:05.047+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T10:47:05.687+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-23T10:47:05.687+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmpnvy544va from /opt/airflow/dags/dbt/weather
[2025-04-23T10:47:05.688+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dbt_transform__dbt_task_group/target/partial_parse.msgpack
[2025-04-23T10:47:05.692+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-23T10:47:05.697+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T10:47:05.697+0000] {config.py:340} INFO - Profile found in cache using profile: /tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3/profiles.yml.
[2025-04-23T10:47:05.699+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['deps', '--project-dir', '/tmp/tmpnvy544va', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpnvy544va
[2025-04-23T10:47:05.727+0000] {logging_mixin.py:190} INFO - 10:47:05  Running with dbt=1.8.7
[2025-04-23T10:47:06.191+0000] {logging_mixin.py:190} INFO - 10:47:06  Installing dbt-labs/dbt_utils
[2025-04-23T10:47:06.999+0000] {logging_mixin.py:190} INFO - 10:47:06  Installed from version 0.9.6
[2025-04-23T10:47:06.999+0000] {logging_mixin.py:190} INFO - 10:47:06  Updated version available: 1.3.0
[2025-04-23T10:47:07.000+0000] {logging_mixin.py:190} INFO - 10:47:07
[2025-04-23T10:47:07.000+0000] {logging_mixin.py:190} INFO - 10:47:07  Updates available for packages: ['dbt-labs/dbt_utils']                 
Update your versions in packages.yml, then run dbt deps
[2025-04-23T10:47:07.948+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'fact_weather_data', '--project-dir', '/tmp/tmpnvy544va', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpnvy544va
[2025-04-23T10:47:07.952+0000] {logging_mixin.py:190} INFO - 10:47:07  Running with dbt=1.8.7
[2025-04-23T10:47:08.026+0000] {logging_mixin.py:190} INFO - 10:47:08  Registered adapter: postgres=1.9.0
[2025-04-23T10:47:08.413+0000] {logging_mixin.py:190} INFO - 10:47:08  Found 5 models, 626 macros
[2025-04-23T10:47:08.414+0000] {logging_mixin.py:190} INFO - 10:47:08
[2025-04-23T10:47:08.458+0000] {logging_mixin.py:190} INFO - 10:47:08  Concurrency: 1 threads (target='dev')
[2025-04-23T10:47:08.458+0000] {logging_mixin.py:190} INFO - 10:47:08
[2025-04-23T10:47:08.459+0000] {logging_mixin.py:190} INFO - 10:47:08  1 of 1 START sql table model transformed.fact_weather_data ..................... [RUN]
[2025-04-23T10:47:08.530+0000] {logging_mixin.py:190} INFO - 10:47:08  1 of 1 OK created sql table model transformed.fact_weather_data ................ [SELECT 192 in 0.07s]
[2025-04-23T10:47:08.534+0000] {logging_mixin.py:190} INFO - 10:47:08
[2025-04-23T10:47:08.534+0000] {logging_mixin.py:190} INFO - 10:47:08  Finished running 1 table model in 0 hours 0 minutes and 0.12 seconds (0.12s).
[2025-04-23T10:47:08.550+0000] {logging_mixin.py:190} INFO - 10:47:08
[2025-04-23T10:47:08.550+0000] {logging_mixin.py:190} INFO - 10:47:08  Completed successfully
[2025-04-23T10:47:08.551+0000] {logging_mixin.py:190} INFO - 10:47:08
[2025-04-23T10:47:08.551+0000] {logging_mixin.py:190} INFO - 10:47:08  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-23T10:47:09.531+0000] {local.py:465} INFO - Inlets: [Dataset(uri='postgres://192.168.88.40:9878/postgres.transformed.dim_district', extra=None), Dataset(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra=None)]
[2025-04-23T10:47:09.531+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://192.168.88.40:9878/postgres.transformed.fact_weather_data', extra=None)]
[2025-04-23T10:47:09.531+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-23T10:47:09.556+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T10:47:09.556+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_transform, task_id=dbt_task_group.fact_weather_data_run, run_id=manual__2025-04-23T10:46:42.794055+00:00, execution_date=20250423T104642, start_date=20250423T104704, end_date=20250423T104709
[2025-04-23T10:47:09.560+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://192.168.88.40:9878/postgres.transformed.fact_weather_data', extra={}) through aliases "dbt_transform__dbt_task_group__fact_weather_data_run"
[2025-04-23T10:47:09.604+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T10:47:09.615+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T10:47:09.617+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
