[2025-04-22T17:26:07.688+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T17:26:07.698+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.temp_run manual__2025-04-22T17:26:05.458553+00:00 [queued]>
[2025-04-22T17:26:07.702+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.temp_run manual__2025-04-22T17:26:05.458553+00:00 [queued]>
[2025-04-22T17:26:07.702+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-22T17:26:07.708+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): dbt_task_group.temp_run> on 2025-04-22 17:26:05.458553+00:00
[2025-04-22T17:26:07.714+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-22T17:26:07.715+0000] {standard_task_runner.py:72} INFO - Started process 413 to run task
[2025-04-22T17:26:07.715+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_transform', 'dbt_task_group.temp_run', 'manual__2025-04-22T17:26:05.458553+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dbtdag.py', '--cfg-path', '/tmp/tmpeee1opct']
[2025-04-22T17:26:07.716+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask dbt_task_group.temp_run
[2025-04-22T17:26:07.739+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_transform.dbt_task_group.temp_run manual__2025-04-22T17:26:05.458553+00:00 [running]> on host afde126db233
[2025-04-22T17:26:07.776+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transform' AIRFLOW_CTX_TASK_ID='dbt_task_group.temp_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T17:26:05.458553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T17:26:05.458553+00:00'
[2025-04-22T17:26:07.776+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T17:26:08.499+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-22T17:26:08.500+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmp_noqzy32 from /opt/airflow/dags/dbt/weather
[2025-04-22T17:26:08.500+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /opt/airflow/dags/dbt/weather/target/partial_parse.msgpack
[2025-04-22T17:26:08.503+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-22T17:26:08.507+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-22T17:26:08.508+0000] {base.py:244} INFO - Using real values for profile default
[2025-04-22T17:26:08.509+0000] {config.py:347} INFO - Profile not found in cache storing and using profile: /tmp/cosmos/profile/ab9f03b35c5599fcc136668296e4e936db5ca98466011b6a1065dd18c4e64b2b/profiles.yml.
[2025-04-22T17:26:08.509+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'temp', '--project-dir', '/tmp/tmp_noqzy32', '--profiles-dir', '/tmp/cosmos/profile/ab9f03b35c5599fcc136668296e4e936db5ca98466011b6a1065dd18c4e64b2b', '--profile', 'default', '--target', 'dev']
 in /tmp/tmp_noqzy32
[2025-04-22T17:26:08.540+0000] {logging_mixin.py:190} INFO - 17:26:08  Running with dbt=1.8.7
[2025-04-22T17:26:08.648+0000] {logging_mixin.py:190} INFO - 17:26:08  Registered adapter: postgres=1.9.0
[2025-04-22T17:26:08.944+0000] {logging_mixin.py:190} INFO - 17:26:08  Unable to do partial parsing because of a version mismatch
[2025-04-22T17:26:09.381+0000] {logging_mixin.py:190} INFO - 17:26:09  Found 1 model, 429 macros
[2025-04-22T17:26:09.382+0000] {logging_mixin.py:190} INFO - 17:26:09
[2025-04-22T17:26:09.419+0000] {logging_mixin.py:190} INFO - 17:26:09  Concurrency: 1 threads (target='dev')
[2025-04-22T17:26:09.419+0000] {logging_mixin.py:190} INFO - 17:26:09
[2025-04-22T17:26:09.420+0000] {logging_mixin.py:190} INFO - 17:26:09  1 of 1 START sql table model public.temp ....................................... [RUN]
[2025-04-22T17:26:09.476+0000] {logging_mixin.py:190} INFO - 17:26:09  1 of 1 OK created sql table model public.temp .................................. [SELECT 3 in 0.05s]
[2025-04-22T17:26:09.481+0000] {logging_mixin.py:190} INFO - 17:26:09
[2025-04-22T17:26:09.481+0000] {logging_mixin.py:190} INFO - 17:26:09  Finished running 1 table model in 0 hours 0 minutes and 0.10 seconds (0.10s).
[2025-04-22T17:26:09.493+0000] {logging_mixin.py:190} INFO - 17:26:09
[2025-04-22T17:26:09.494+0000] {logging_mixin.py:190} INFO - 17:26:09  Completed successfully
[2025-04-22T17:26:09.494+0000] {logging_mixin.py:190} INFO - 17:26:09
[2025-04-22T17:26:09.494+0000] {logging_mixin.py:190} INFO - 17:26:09  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-22T17:26:10.958+0000] {local.py:465} INFO - Inlets: []
[2025-04-22T17:26:10.958+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://192.168.88.40:9878/postgres.public.temp', extra=None)]
[2025-04-22T17:26:10.958+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-22T17:26:10.981+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T17:26:10.981+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_transform, task_id=dbt_task_group.temp_run, run_id=manual__2025-04-22T17:26:05.458553+00:00, execution_date=20250422T172605, start_date=20250422T172607, end_date=20250422T172610
[2025-04-22T17:26:10.986+0000] {taskinstance.py:3054} WARNING - Created a new DatasetModel(uri='postgres://192.168.88.40:9878/postgres.public.temp', extra={}) as it did not exist.
[2025-04-22T17:26:10.988+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://192.168.88.40:9878/postgres.public.temp', extra={}) through aliases "dbt_transform__dbt_task_group__temp_run"
[2025-04-22T17:26:11.054+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T17:26:11.065+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T17:26:11.067+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
