[2025-04-23T09:08:40.302+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T09:08:40.309+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.check_if_table_exists manual__2025-04-23T09:08:39.516731+00:00 [queued]>
[2025-04-23T09:08:40.312+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.check_if_table_exists manual__2025-04-23T09:08:39.516731+00:00 [queued]>
[2025-04-23T09:08:40.312+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T09:08:40.318+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): check_if_table_exists> on 2025-04-23 09:08:39.516731+00:00
[2025-04-23T09:08:40.324+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3063) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T09:08:40.325+0000] {standard_task_runner.py:72} INFO - Started process 3065 to run task
[2025-04-23T09:08:40.325+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'check_if_table_exists', 'manual__2025-04-23T09:08:39.516731+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmpv07lsr6n']
[2025-04-23T09:08:40.327+0000] {standard_task_runner.py:105} INFO - Job 182: Subtask check_if_table_exists
[2025-04-23T09:08:40.349+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.check_if_table_exists manual__2025-04-23T09:08:39.516731+00:00 [running]> on host eb276ba0497d
[2025-04-23T09:08:40.389+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T09:08:39.516731+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T09:08:39.516731+00:00'
[2025-04-23T09:08:40.390+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T09:08:40.396+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-04-23T09:08:40.407+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T09:08:40.407+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data_daily, task_id=check_if_table_exists, run_id=manual__2025-04-23T09:08:39.516731+00:00, execution_date=20250423T090839, start_date=20250423T090840, end_date=20250423T090840
[2025-04-23T09:08:40.458+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T09:08:40.466+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T09:08:40.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
