[2025-04-23T06:14:05.274+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T06:14:05.283+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data.load_to_postgres manual__2025-04-23T05:59:57.139793+00:00 [queued]>
[2025-04-23T06:14:05.286+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data.load_to_postgres manual__2025-04-23T05:59:57.139793+00:00 [queued]>
[2025-04-23T06:14:05.286+0000] {taskinstance.py:2867} INFO - Starting attempt 6 of 7
[2025-04-23T06:14:05.292+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): load_to_postgres> on 2025-04-23 05:59:57.139793+00:00
[2025-04-23T06:14:05.299+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8495) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T06:14:05.300+0000] {standard_task_runner.py:72} INFO - Started process 8497 to run task
[2025-04-23T06:14:05.300+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data', 'load_to_postgres', 'manual__2025-04-23T05:59:57.139793+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/el.py', '--cfg-path', '/tmp/tmp17s29hzx']
[2025-04-23T06:14:05.302+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask load_to_postgres
[2025-04-23T06:14:05.325+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data.load_to_postgres manual__2025-04-23T05:59:57.139793+00:00 [running]> on host eb276ba0497d
[2025-04-23T06:14:05.403+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T05:59:57.139793+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T05:59:57.139793+00:00'
[2025-04-23T06:14:05.404+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T06:14:05.410+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T06:14:05.416+0000] {el.py:173} INFO - Weather data loaded successfully into PostgreSQL
[2025-04-23T06:14:05.416+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T06:14:05.422+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T06:14:05.422+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data, task_id=load_to_postgres, run_id=manual__2025-04-23T05:59:57.139793+00:00, execution_date=20250423T055957, start_date=20250423T061405, end_date=20250423T061405
[2025-04-23T06:14:05.473+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T06:14:05.482+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T06:14:05.483+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
